sudo: required
services:
  - docker

before_install:
  - docker build -t pn/react-docker -f Dockerfile .

script:
  - docker run -e CI=true pn/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-046101455511"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
